name: fastaudio
channels:
  - defaults
  - fastai
  - pytorch
  - conda-forge
dependencies:
  - python>=3.6
  - fastai>=2.0
  - pytorch>=1.6
  - torchaudio>=0.6
  - cudatoolkit=10.1
  - librosa=0.7.2
  - fastcore==1.0.8
  - numba=0.48.0
  - pip>=20.2
  - IPython>=7.16
  - pip:
    - colorednoise>=1.1
    - git+https://github.com/fastaudio/fastaudio.git
